// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/metadata/proto/metadata.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Encryption int32

const (
	Encryption_NONE    Encryption = 0 // No encryption
	Encryption_RCLONE  Encryption = 1 // Rclone encryption
	Encryption_HEADERS Encryption = 2 // Headers encryption
	Encryption_AES     Encryption = 3 // Generic AES-CBC encryption (for RAR, 7z, etc.)
)

// Enum value maps for Encryption.
var (
	Encryption_name = map[int32]string{
		0: "NONE",
		1: "RCLONE",
		2: "HEADERS",
		3: "AES",
	}
	Encryption_value = map[string]int32{
		"NONE":    0,
		"RCLONE":  1,
		"HEADERS": 2,
		"AES":     3,
	}
)

func (x Encryption) Enum() *Encryption {
	p := new(Encryption)
	*p = x
	return p
}

func (x Encryption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encryption) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_metadata_proto_metadata_proto_enumTypes[0].Descriptor()
}

func (Encryption) Type() protoreflect.EnumType {
	return &file_internal_metadata_proto_metadata_proto_enumTypes[0]
}

func (x Encryption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encryption.Descriptor instead.
func (Encryption) EnumDescriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{0}
}

// FileStatus represents the health status of a file
type FileStatus int32

const (
	FileStatus_FILE_STATUS_UNSPECIFIED FileStatus = 0
	FileStatus_FILE_STATUS_HEALTHY     FileStatus = 1 // All segments available and file is complete
	FileStatus_FILE_STATUS_CORRUPTED   FileStatus = 3 // Segments missing or corrupted
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_STATUS_UNSPECIFIED",
		1: "FILE_STATUS_HEALTHY",
		3: "FILE_STATUS_CORRUPTED",
	}
	FileStatus_value = map[string]int32{
		"FILE_STATUS_UNSPECIFIED": 0,
		"FILE_STATUS_HEALTHY":     1,
		"FILE_STATUS_CORRUPTED":   3,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_metadata_proto_metadata_proto_enumTypes[1].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_internal_metadata_proto_metadata_proto_enumTypes[1]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{1}
}

// SegmentData contains Usenet segment information with byte offsets
type SegmentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentSize   int64                  `protobuf:"varint,1,opt,name=segment_size,json=segmentSize,proto3" json:"segment_size,omitempty"` // Size of the segment in bytes
	StartOffset   int64                  `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"` // Start byte offset in the data stream
	EndOffset     int64                  `protobuf:"varint,4,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`       // End byte offset in the data stream
	Id            string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`                                       // Usenet message ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentData) Reset() {
	*x = SegmentData{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentData) ProtoMessage() {}

func (x *SegmentData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentData.ProtoReflect.Descriptor instead.
func (*SegmentData) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentData) GetSegmentSize() int64 {
	if x != nil {
		return x.SegmentSize
	}
	return 0
}

func (x *SegmentData) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *SegmentData) GetEndOffset() int64 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *SegmentData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Par2FileReference stores information about PAR2 repair files
type Par2FileReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                          // PAR2 filename (e.g., "movie.par2", "movie.vol01+02.par2")
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`         // Size of the PAR2 file in bytes
	SegmentData   []*SegmentData         `protobuf:"bytes,3,rep,name=segment_data,json=segmentData,proto3" json:"segment_data,omitempty"` // Usenet segments containing PAR2 data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Par2FileReference) Reset() {
	*x = Par2FileReference{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Par2FileReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Par2FileReference) ProtoMessage() {}

func (x *Par2FileReference) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Par2FileReference.ProtoReflect.Descriptor instead.
func (*Par2FileReference) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *Par2FileReference) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Par2FileReference) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Par2FileReference) GetSegmentData() []*SegmentData {
	if x != nil {
		return x.SegmentData
	}
	return nil
}

// BlurayMetadata contains information for extracting specific streams from Blu-ray disc structures
type BlurayMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetM2TsFile string                 `protobuf:"bytes,1,opt,name=target_m2ts_file,json=targetM2tsFile,proto3" json:"target_m2ts_file,omitempty"` // Target .m2ts file to extract (e.g., "00000.m2ts")
	BdmvPath       string                 `protobuf:"bytes,2,opt,name=bdmv_path,json=bdmvPath,proto3" json:"bdmv_path,omitempty"`                     // Path to BDMV folder within archive (e.g., "BDMV/")
	PlaylistName   string                 `protobuf:"bytes,3,opt,name=playlist_name,json=playlistName,proto3" json:"playlist_name,omitempty"`         // Human-readable name from playlist (e.g., "Main Feature")
	M2TsOffset     int64                  `protobuf:"varint,4,opt,name=m2ts_offset,json=m2tsOffset,proto3" json:"m2ts_offset,omitempty"`              // Offset of .m2ts file within BDMV structure
	M2TsSize       int64                  `protobuf:"varint,5,opt,name=m2ts_size,json=m2tsSize,proto3" json:"m2ts_size,omitempty"`                    // Size of the .m2ts file
	ClipInfoFile   string                 `protobuf:"bytes,6,opt,name=clip_info_file,json=clipInfoFile,proto3" json:"clip_info_file,omitempty"`       // Associated .clpi file name for metadata
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlurayMetadata) Reset() {
	*x = BlurayMetadata{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlurayMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlurayMetadata) ProtoMessage() {}

func (x *BlurayMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlurayMetadata.ProtoReflect.Descriptor instead.
func (*BlurayMetadata) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *BlurayMetadata) GetTargetM2TsFile() string {
	if x != nil {
		return x.TargetM2TsFile
	}
	return ""
}

func (x *BlurayMetadata) GetBdmvPath() string {
	if x != nil {
		return x.BdmvPath
	}
	return ""
}

func (x *BlurayMetadata) GetPlaylistName() string {
	if x != nil {
		return x.PlaylistName
	}
	return ""
}

func (x *BlurayMetadata) GetM2TsOffset() int64 {
	if x != nil {
		return x.M2TsOffset
	}
	return 0
}

func (x *BlurayMetadata) GetM2TsSize() int64 {
	if x != nil {
		return x.M2TsSize
	}
	return 0
}

func (x *BlurayMetadata) GetClipInfoFile() string {
	if x != nil {
		return x.ClipInfoFile
	}
	return ""
}

// FileMetadata represents a single virtual file in the filesystem
// The filename comes from the actual metadata filename on disk
type FileMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FileSize       int64                  `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`                   // Size of the virtual file in bytes
	SourceNzbPath  string                 `protobuf:"bytes,2,opt,name=source_nzb_path,json=sourceNzbPath,proto3" json:"source_nzb_path,omitempty"`   // Path to source NZB file
	Status         FileStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=metadata.FileStatus" json:"status,omitempty"`              // Health status of the file
	CreatedAt      int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                // Unix timestamp when metadata was created
	ModifiedAt     int64                  `protobuf:"varint,5,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`             // Unix timestamp when last modified
	Password       string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`                                    // Password for rclone encrypted files
	Salt           string                 `protobuf:"bytes,7,opt,name=salt,proto3" json:"salt,omitempty"`                                            // Salt for rclone encrypted files
	Encryption     Encryption             `protobuf:"varint,8,opt,name=encryption,proto3,enum=metadata.Encryption" json:"encryption,omitempty"`      // Encryption type used for the file
	SegmentData    []*SegmentData         `protobuf:"bytes,9,rep,name=segment_data,json=segmentData,proto3" json:"segment_data,omitempty"`           // Segment information (lazy-loaded)
	AesKey         []byte                 `protobuf:"bytes,10,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`                         // AES encryption key (for AES-encrypted archives)
	AesIv          []byte                 `protobuf:"bytes,11,opt,name=aes_iv,json=aesIv,proto3" json:"aes_iv,omitempty"`                            // AES initialization vector (for AES-encrypted archives)
	ReleaseDate    int64                  `protobuf:"varint,12,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`         // Unix timestamp of the original Usenet post release date
	Par2Files      []*Par2FileReference   `protobuf:"bytes,13,rep,name=par2_files,json=par2Files,proto3" json:"par2_files,omitempty"`                // Associated PAR2 repair files
	BlurayMetadata *BlurayMetadata        `protobuf:"bytes,14,opt,name=bluray_metadata,json=blurayMetadata,proto3" json:"bluray_metadata,omitempty"` // Blu-ray specific metadata (if file is from BDMV structure)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_metadata_proto_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_internal_metadata_proto_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *FileMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileMetadata) GetSourceNzbPath() string {
	if x != nil {
		return x.SourceNzbPath
	}
	return ""
}

func (x *FileMetadata) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_STATUS_UNSPECIFIED
}

func (x *FileMetadata) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileMetadata) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *FileMetadata) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *FileMetadata) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *FileMetadata) GetEncryption() Encryption {
	if x != nil {
		return x.Encryption
	}
	return Encryption_NONE
}

func (x *FileMetadata) GetSegmentData() []*SegmentData {
	if x != nil {
		return x.SegmentData
	}
	return nil
}

func (x *FileMetadata) GetAesKey() []byte {
	if x != nil {
		return x.AesKey
	}
	return nil
}

func (x *FileMetadata) GetAesIv() []byte {
	if x != nil {
		return x.AesIv
	}
	return nil
}

func (x *FileMetadata) GetReleaseDate() int64 {
	if x != nil {
		return x.ReleaseDate
	}
	return 0
}

func (x *FileMetadata) GetPar2Files() []*Par2FileReference {
	if x != nil {
		return x.Par2Files
	}
	return nil
}

func (x *FileMetadata) GetBlurayMetadata() *BlurayMetadata {
	if x != nil {
		return x.BlurayMetadata
	}
	return nil
}

var File_internal_metadata_proto_metadata_proto protoreflect.FileDescriptor

const file_internal_metadata_proto_metadata_proto_rawDesc = "" +
	"\n" +
	"&internal/metadata/proto/metadata.proto\x12\bmetadata\"\x82\x01\n" +
	"\vSegmentData\x12!\n" +
	"\fsegment_size\x18\x01 \x01(\x03R\vsegmentSize\x12!\n" +
	"\fstart_offset\x18\x03 \x01(\x03R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x04 \x01(\x03R\tendOffset\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\"\x86\x01\n" +
	"\x11Par2FileReference\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x128\n" +
	"\fsegment_data\x18\x03 \x03(\v2\x15.metadata.SegmentDataR\vsegmentData\"\xe0\x01\n" +
	"\x0eBlurayMetadata\x12(\n" +
	"\x10target_m2ts_file\x18\x01 \x01(\tR\x0etargetM2tsFile\x12\x1b\n" +
	"\tbdmv_path\x18\x02 \x01(\tR\bbdmvPath\x12#\n" +
	"\rplaylist_name\x18\x03 \x01(\tR\fplaylistName\x12\x1f\n" +
	"\vm2ts_offset\x18\x04 \x01(\x03R\n" +
	"m2tsOffset\x12\x1b\n" +
	"\tm2ts_size\x18\x05 \x01(\x03R\bm2tsSize\x12$\n" +
	"\x0eclip_info_file\x18\x06 \x01(\tR\fclipInfoFile\"\xb3\x04\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_size\x18\x01 \x01(\x03R\bfileSize\x12&\n" +
	"\x0fsource_nzb_path\x18\x02 \x01(\tR\rsourceNzbPath\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.metadata.FileStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vmodified_at\x18\x05 \x01(\x03R\n" +
	"modifiedAt\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x12\n" +
	"\x04salt\x18\a \x01(\tR\x04salt\x124\n" +
	"\n" +
	"encryption\x18\b \x01(\x0e2\x14.metadata.EncryptionR\n" +
	"encryption\x128\n" +
	"\fsegment_data\x18\t \x03(\v2\x15.metadata.SegmentDataR\vsegmentData\x12\x17\n" +
	"\aaes_key\x18\n" +
	" \x01(\fR\x06aesKey\x12\x15\n" +
	"\x06aes_iv\x18\v \x01(\fR\x05aesIv\x12!\n" +
	"\frelease_date\x18\f \x01(\x03R\vreleaseDate\x12:\n" +
	"\n" +
	"par2_files\x18\r \x03(\v2\x1b.metadata.Par2FileReferenceR\tpar2Files\x12A\n" +
	"\x0fbluray_metadata\x18\x0e \x01(\v2\x18.metadata.BlurayMetadataR\x0eblurayMetadata*8\n" +
	"\n" +
	"Encryption\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06RCLONE\x10\x01\x12\v\n" +
	"\aHEADERS\x10\x02\x12\a\n" +
	"\x03AES\x10\x03*]\n" +
	"\n" +
	"FileStatus\x12\x1b\n" +
	"\x17FILE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FILE_STATUS_HEALTHY\x10\x01\x12\x19\n" +
	"\x15FILE_STATUS_CORRUPTED\x10\x03B\x04Z\x02./b\x06proto3"

var (
	file_internal_metadata_proto_metadata_proto_rawDescOnce sync.Once
	file_internal_metadata_proto_metadata_proto_rawDescData []byte
)

func file_internal_metadata_proto_metadata_proto_rawDescGZIP() []byte {
	file_internal_metadata_proto_metadata_proto_rawDescOnce.Do(func() {
		file_internal_metadata_proto_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_metadata_proto_metadata_proto_rawDesc), len(file_internal_metadata_proto_metadata_proto_rawDesc)))
	})
	return file_internal_metadata_proto_metadata_proto_rawDescData
}

var file_internal_metadata_proto_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_metadata_proto_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_metadata_proto_metadata_proto_goTypes = []any{
	(Encryption)(0),           // 0: metadata.Encryption
	(FileStatus)(0),           // 1: metadata.FileStatus
	(*SegmentData)(nil),       // 2: metadata.SegmentData
	(*Par2FileReference)(nil), // 3: metadata.Par2FileReference
	(*BlurayMetadata)(nil),    // 4: metadata.BlurayMetadata
	(*FileMetadata)(nil),      // 5: metadata.FileMetadata
}
var file_internal_metadata_proto_metadata_proto_depIdxs = []int32{
	2, // 0: metadata.Par2FileReference.segment_data:type_name -> metadata.SegmentData
	1, // 1: metadata.FileMetadata.status:type_name -> metadata.FileStatus
	0, // 2: metadata.FileMetadata.encryption:type_name -> metadata.Encryption
	2, // 3: metadata.FileMetadata.segment_data:type_name -> metadata.SegmentData
	3, // 4: metadata.FileMetadata.par2_files:type_name -> metadata.Par2FileReference
	4, // 5: metadata.FileMetadata.bluray_metadata:type_name -> metadata.BlurayMetadata
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_metadata_proto_metadata_proto_init() }
func file_internal_metadata_proto_metadata_proto_init() {
	if File_internal_metadata_proto_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_metadata_proto_metadata_proto_rawDesc), len(file_internal_metadata_proto_metadata_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_metadata_proto_metadata_proto_goTypes,
		DependencyIndexes: file_internal_metadata_proto_metadata_proto_depIdxs,
		EnumInfos:         file_internal_metadata_proto_metadata_proto_enumTypes,
		MessageInfos:      file_internal_metadata_proto_metadata_proto_msgTypes,
	}.Build()
	File_internal_metadata_proto_metadata_proto = out.File
	file_internal_metadata_proto_metadata_proto_goTypes = nil
	file_internal_metadata_proto_metadata_proto_depIdxs = nil
}
