package par2gen_test

import (
	"bytes"
	"crypto/md5"
	"testing"

	"github.com/javi11/altmount/internal/importer/parser/par2"
	"github.com/javi11/altmount/internal/testsupport/par2gen"
)

func TestBuild_roundtrip(t *testing.T) {
	content := bytes.Repeat([]byte("x"), 32000)
	entries := []par2gen.FileEntry{
		{Name: "Real.Movie.2024.mkv", Content: content},
		{Name: "Real.Movie.2024.srt", Content: []byte("subtitle data")},
	}

	data := par2gen.Build(entries...)
	if len(data) == 0 {
		t.Fatal("Build returned empty bytes")
	}

	// Verify magic bytes are present at offset 0.
	if !par2.HasMagicBytes(data) {
		t.Fatal("generated data does not start with PAR2 magic")
	}

	// Parse the generated bytes through the real packet reader.
	r := par2.NewPacketReader(bytes.NewReader(data))

	var found []string
	for {
		hdr, err := r.ReadHeader()
		if err != nil {
			break
		}
		if hdr.Type != par2.PacketTypeFileDesc {
			if err := r.SkipPacketBody(hdr); err != nil {
				t.Fatalf("SkipPacketBody: %v", err)
			}
			continue
		}
		desc, err := r.ReadFileDescriptor(hdr)
		if err != nil {
			t.Fatalf("ReadFileDescriptor: %v", err)
		}
		found = append(found, desc.Name)

		// Verify Hash16k matches what the importer would compute.
		padded := make([]byte, 16384)
		copy(padded, entries[len(found)-1].Content)
		want := md5.Sum(padded)
		if desc.Hash16k != want {
			t.Errorf("entry %q: Hash16k mismatch", desc.Name)
		}
		// Verify Length.
		if desc.Length != uint64(len(entries[len(found)-1].Content)) {
			t.Errorf("entry %q: Length = %d, want %d", desc.Name, desc.Length, len(entries[len(found)-1].Content))
		}
	}

	if len(found) != len(entries) {
		t.Fatalf("parsed %d descriptors, want %d", len(found), len(entries))
	}
	for i, e := range entries {
		if found[i] != e.Name {
			t.Errorf("descriptor[%d].Name = %q, want %q", i, found[i], e.Name)
		}
	}
}

func TestBuild_shortContent(t *testing.T) {
	// Content < 16 KB: hash should still use zero-padded 16384-byte block.
	content := []byte("short file")
	data := par2gen.Build(par2gen.FileEntry{Name: "tiny.txt", Content: content})

	r := par2.NewPacketReader(bytes.NewReader(data))
	hdr, err := r.ReadHeader()
	if err != nil {
		t.Fatalf("ReadHeader: %v", err)
	}
	desc, err := r.ReadFileDescriptor(hdr)
	if err != nil {
		t.Fatalf("ReadFileDescriptor: %v", err)
	}

	padded := make([]byte, 16384)
	copy(padded, content)
	want := md5.Sum(padded)
	if desc.Hash16k != want {
		t.Error("short content: Hash16k not zero-padded correctly")
	}
	if desc.Length != uint64(len(content)) {
		t.Errorf("Length = %d, want %d", desc.Length, len(content))
	}
}
