import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "4. API/altmount-api",
    },
    {
      type: "category",
      label: "ARRs",
      items: [
        {
          type: "doc",
          id: "4. API/register-arr-download-clients",
          label: "Register ARR download clients",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/test-arr-download-client-connections",
          label: "Test ARR download client connections",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-arr-health",
          label: "Get ARR health",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/list-arr-instances",
          label: "List ARR instances",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/test-arr-connection",
          label: "Test ARR connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-arr-instance",
          label: "Get ARR instance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/get-arr-statistics",
          label: "Get ARR statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/handle-arr-webhook",
          label: "Handle ARR webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/register-arr-webhooks",
          label: "Register ARR webhooks",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Auth",
      items: [
        {
          type: "doc",
          id: "4. API/get-authentication-configuration",
          label: "Get authentication configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/login-with-username-and-password",
          label: "Login with username and password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/register-a-new-user",
          label: "Register a new user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/check-registration-status",
          label: "Check registration status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Config",
      items: [
        {
          type: "doc",
          id: "4. API/get-current-configuration",
          label: "Get current configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/update-full-configuration",
          label: "Update full configuration",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "4. API/reload-configuration-from-disk",
          label: "Reload configuration from disk",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/validate-configuration",
          label: "Validate configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/patch-a-configuration-section",
          label: "Patch a configuration section",
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Files",
      items: [
        {
          type: "doc",
          id: "4. API/get-active-streams",
          label: "Get active streams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/kill-an-active-stream",
          label: "Kill an active stream",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/batch-export-nzb-files-as-zip",
          label: "Batch export NZB files as ZIP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/export-file-metadata-as-nzb",
          label: "Export file metadata as NZB",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/get-file-metadata",
          label: "Get file metadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/get-stream-history",
          label: "Get stream history",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "FUSE",
      items: [
        {
          type: "doc",
          id: "4. API/force-stop-fuse-mount",
          label: "Force stop FUSE mount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/start-fuse-mount",
          label: "Start FUSE mount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-fuse-mount-status",
          label: "Get FUSE mount status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/stop-fuse-mount",
          label: "Stop FUSE mount",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Health",
      items: [
        {
          type: "doc",
          id: "4. API/list-health-records",
          label: "List health records",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/bulk-delete-health-records",
          label: "Bulk delete health records",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/bulk-trigger-file-repairs",
          label: "Bulk trigger file repairs",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/bulk-restart-health-checks",
          label: "Bulk restart health checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/add-file-to-health-check-queue",
          label: "Add file to health check queue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/cleanup-old-health-records",
          label: "Cleanup old health records",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/list-corrupted-files",
          label: "List corrupted files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/cancel-library-sync",
          label: "Cancel library sync",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/dry-run-library-sync",
          label: "Dry run library sync",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/check-if-library-sync-is-needed",
          label: "Check if library sync is needed",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/start-library-sync",
          label: "Start library sync",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-library-sync-status",
          label: "Get library sync status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/regenerate-symlinks-for-health-records",
          label: "Regenerate symlinks for health records",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/reset-all-health-checks",
          label: "Reset all health checks",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-health-statistics",
          label: "Get health statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/get-health-worker-status",
          label: "Get health worker status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/get-health-record",
          label: "Get health record",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/delete-health-record",
          label: "Delete health record",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/cancel-active-health-check",
          label: "Cancel active health check",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/immediately-check-file-health",
          label: "Immediately check file health",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/set-health-check-priority",
          label: "Set health check priority",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/trigger-file-repair",
          label: "Trigger file repair",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/unmask-health-record",
          label: "Unmask health record",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Import",
      items: [
        {
          type: "doc",
          id: "4. API/manually-import-a-file",
          label: "Manually import a file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-import-history",
          label: "Get import history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/clear-import-history",
          label: "Clear import history",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/start-manual-scan",
          label: "Start manual scan",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/cancel-active-scan",
          label: "Cancel active scan",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/get-scan-status",
          label: "Get scan status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "NZBDav",
      items: [
        {
          type: "doc",
          id: "4. API/import-nzb-dav-database",
          label: "Import NzbDav database",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/cancel-nzb-dav-import",
          label: "Cancel NzbDav import",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/reset-nzb-dav-import-status",
          label: "Reset NzbDav import status",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-nzb-dav-import-status",
          label: "Get NzbDav import status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "NZB",
      items: [
        {
          type: "doc",
          id: "4. API/upload-nzb-and-get-stream-ur-ls",
          label: "Upload NZB and get stream URLs",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Providers",
      items: [
        {
          type: "doc",
          id: "4. API/create-nntp-provider",
          label: "Create NNTP provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/reorder-nntp-providers",
          label: "Reorder NNTP providers",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "4. API/test-nntp-provider-connection",
          label: "Test NNTP provider connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/update-nntp-provider",
          label: "Update NNTP provider",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "4. API/delete-nntp-provider",
          label: "Delete NNTP provider",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Queue",
      items: [
        {
          type: "doc",
          id: "4. API/list-queue-items",
          label: "List queue items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/bulk-delete-queue-items",
          label: "Bulk delete queue items",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/bulk-cancel-queue-items",
          label: "Bulk cancel queue items",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/bulk-restart-queue-items",
          label: "Bulk restart queue items",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/clear-completed-queue-items",
          label: "Clear completed queue items",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/clear-failed-queue-items",
          label: "Clear failed queue items",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/clear-pending-queue-items",
          label: "Clear pending queue items",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/stream-queue-progress-sse",
          label: "Stream queue progress (SSE)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/get-queue-statistics",
          label: "Get queue statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/get-queue-historical-statistics",
          label: "Get queue historical statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/add-test-queue-item",
          label: "Add test queue item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/upload-nzb-file-to-queue",
          label: "Upload NZB file to queue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/search-and-queue-nzb-by-name",
          label: "Search and queue NZB by name",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/upload-nzblnk-links-to-queue",
          label: "Upload NZBLNK links to queue",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-queue-item",
          label: "Get queue item",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/delete-queue-item",
          label: "Delete queue item",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/cancel-queue-item",
          label: "Cancel queue item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/download-nzb-file-for-queue-item",
          label: "Download NZB file for queue item",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/update-queue-item-priority",
          label: "Update queue item priority",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "4. API/retry-queue-item",
          label: "Retry queue item",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "RClone",
      items: [
        {
          type: "doc",
          id: "4. API/clear-r-clone-cache",
          label: "Clear RClone cache",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "4. API/start-r-clone-mount",
          label: "Start RClone mount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-r-clone-mount-status",
          label: "Get RClone mount status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/stop-r-clone-mount",
          label: "Stop RClone mount",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/test-r-clone-mount-configuration",
          label: "Test RClone mount configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/test-r-clone-rc-connection",
          label: "Test RClone RC connection",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "System",
      items: [
        {
          type: "doc",
          id: "4. API/browse-filesystem",
          label: "Browse filesystem",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/system-cleanup",
          label: "System cleanup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-system-health-status",
          label: "Get system health status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/get-nntp-pool-metrics",
          label: "Get NNTP pool metrics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/restart-the-server",
          label: "Restart the server",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-system-statistics",
          label: "Get system statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/reset-system-statistics",
          label: "Reset system statistics",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/apply-system-update",
          label: "Apply system update",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/get-update-status",
          label: "Get update status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "User",
      items: [
        {
          type: "doc",
          id: "4. API/get-current-user",
          label: "Get current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/regenerate-api-key",
          label: "Regenerate API key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/logout-current-user",
          label: "Logout current user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "4. API/change-own-password",
          label: "Change own password",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "4. API/refresh-jwt-token",
          label: "Refresh JWT token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Stremio",
      items: [
        {
          type: "doc",
          id: "4. API/stremio-addon-manifest",
          label: "Stremio addon manifest",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/stremio-play-queue-nzb-and-redirect-to-stream",
          label: "Stremio play — queue NZB and redirect to stream",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "4. API/stremio-stream-lookup",
          label: "Stremio stream lookup",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
